#!/usr/bin/env bash

#This script displays "Best School" x10 using a while loop.
#On the 9th iteration, it displays "Hi" before "Best School".

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 8 ]
  	then
    		echo "Hi"
  	fi
	echo "Best School"
  	(( i++ ))
done
